# Generated by Django 6.0.2 on 2026-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(choices=[(0, 'Prefiero no decir '), (2, 'Hombre '), (1, 'Mujer ')], default=0)),
                ('fecha_nacimiento', models.DateField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_aplicacion.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.IntegerField(choices=[(0, 'Prefiero no decir '), (2, 'Hombre '), (1, 'Mujer ')], default=0)),
                ('fecha_nacimiento', models.DateField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_aplicacion.escuela')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_aplicacion.maestro')),
            ],
        ),
    ]
